baseURL = "https://www.writeingo.com/"
languageCode = "en-us"
title = "Write in GO"
disqusShortname = "reversance"

SectionPagesMenu = "main"

[params]
  author = "Radek (LuxuryPro)"
  description = "Blog about GO programming language"
  googleAnalytics = "UA-97780102-1"
  ISO8601 = "2006-01-02T15:04:05CEST"
  [params.social]
    twitter = "reversance"

[permalinks]
	blog = "/blog/:slug/"

[taxonomies]
tag = "tags"

[[menu.main]]
    name = "Blog"
    identifier = "blog"
    url = "/blog/"

