baseURL = "https://www.iops.tech/"
languageCode = "en-us"
title = "iops.tech"

[params]
  author = "Radosław Załuska"
  description = "DevOps Blog by Radosław Załuska"
  googleAnalytics = "G-PGPLFBD7KR"
  ISO8601 = "2006-01-02T15:04:05CEST"

[permalinks]
	blog = "/blog/:slug/"

[taxonomies]
tag = "tags"
