baseURL = "https://www.writeingo.com/"
languageCode = "en-us"
title = "Write in Go"
disqusShortname = "writeingo"

[params]
  author = "Radosław Załuska"
  description = "Blog about Golang"
  googleAnalytics = "UA-97780102-1"
  ISO8601 = "2006-01-02T15:04:05CEST"
  [params.social]
    twitter = "rzaluska"

[permalinks]
	blog = "/blog/:slug/"

[taxonomies]
tag = "tags"
