baseURL = "https://www.reversance.com/"
languageCode = "en-us"
title = "Reversance blog"
disqusShortname = "reversance"


[params]
  author = "Radek (LuxuryPro)"
  githubUser = "LuxuryPro"
  description = "Linux - Android - Programming - Security - Reverse Engineering"
  googleAnalytics = "UA-97780102-1"

[permalinks]
	post = "/:year/:month/:day/:slug/"

[taxonomies]
tag = "tags"

