baseURL = "https://jaffamonkeyblog.netlify.com/"
languageCode = "en-us"
title = "Write in Go"
disqusShortname = "writeingo"

[params]
  subtitle = "jaffamonkey blog"
  author = "jaffamonkey"
  description = "test engineering and devops"
  googleAnalytics = "UA-97780102-1"
  ISO8601 = "2006-01-02T15:04:05CEST"
  [params.social]
    twitter = "jaffamonkey"

[permalinks]
	blog = "/blog/:slug/"

[taxonomies]
tag = "tags"

