baseURL = "https://www.reversance.com/"
languageCode = "en-us"
title = "Reversance"
disqusShortname = "reversance"

SectionPagesMenu = "main"

[params]
  author = "Radek (LuxuryPro)"
  githubUser = "LuxuryPro"
  description = "Blog about Linux - Android - Programming - Security - Reverse Engineering"
  googleAnalytics = "UA-97780102-1"
  ISO8601 = "2006-01-02T15:04:05CEST"
  [params.social]
    twitter = "reversance"

[permalinks]
	blog = "/blog/:slug/"

[taxonomies]
tag = "tags"

[[menu.main]]
        name = "Blog"
        identifier = "blog"
        url = "/blog/"

