baseURL = "https://devopsguy.info/"
languageCode = "en-us"
title = "devopsguy.info"

[params]
  author = "Radosław Załuska"
  description = "Blog"
  googleAnalytics = "G-QX0DBL5CG4"
  ISO8601 = "2006-01-02T15:04:05CEST"

[permalinks]
	blog = "/blog/:slug/"

[taxonomies]
tag = "tags"
